spring.application.name=SmartQueueManagement
spring.datasource.url=jdbc:mysql://localhost:3306/smart_queue_management
spring.datasource.username=root
spring.datasource.password= 262006Sa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true